# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'On'), (2, 'Off')], default=2),
        ),
        migrations.AddField(
            model_name='arduino',
            name='temperature',
            field=models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
